# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-05 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='foundationID',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
