# Generated by Django 2.2.6 on 2019-10-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0002_foundation_foundationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundation',
            name='foundationID',
        ),
    ]
