# Generated by Django 2.2.6 on 2019-11-11 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0002_auto_20191110_2339'),
        ('foundations', '0002_auto_20191104_0002'),
    ]

    operations = [
    ]
