# Generated by Django 2.2.6 on 2019-11-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0003_merge_20191111_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='foundation',
            name='img',
            field=models.FileField(default='', upload_to='test'),
        ),
    ]
