# Generated by Django 2.2.6 on 2019-11-12 00:21

import conduit.apps.foundations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0004_foundation_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundation',
            name='img',
            field=models.FileField(blank=True, upload_to=conduit.apps.foundations.models.upload_image_to),
        ),
    ]
