# Generated by Django 2.2.6 on 2019-11-12 03:29

import conduit.apps.grants.models.grantModel
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, upload_to=conduit.apps.grants.models.grantModel.upload_image_to)),
                ('isPreFunded', models.BooleanField(default=False)),
                ('numberOfGrantees', models.IntegerField(default=1)),
                ('amountPerGrantee', models.IntegerField()),
                ('nonFinancialRewards', models.BooleanField(default=False)),
                ('applicationsStartDate', models.DateField()),
                ('applicationsEndDate', models.DateField()),
                ('description', models.TextField()),
                ('externalWebsite', models.TextField(default='')),
                ('otherDetails', models.TextField(default='')),
                ('supportingData', models.TextField(default='')),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
    ]
