# Generated by Django 2.2.6 on 2019-11-10 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundations', '0002_auto_20191110_2339'),
        ('profiles', '0001_initial'),
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantapplication',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='grantapplication',
            name='grant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='grants.Grant'),
        ),
        migrations.AddField(
            model_name='grant',
            name='foundation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='foundations.Foundation'),
        ),
        migrations.AddField(
            model_name='grant',
            name='tags',
            field=models.ManyToManyField(related_name='grants', to='grants.Tag'),
        ),
    ]
