# Generated by Django 2.2.6 on 2019-11-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_merge_20191111_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='amountPerGrantee',
            field=models.IntegerField(),
        ),
    ]
