# Generated by Django 2.2.6 on 2019-11-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_auto_20191111_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='img',
            field=models.FileField(blank=True, upload_to='grant-<django.db.models.fields.SlugField>'),
        ),
    ]
