from django.db import models
from conduit.apps.core.models import TimestampedModel
from django.utils.timezone import now

from ..common.grantState import GrantState

DEFAULT_NUMBER_OF_APPLICANTS = 1


def upload_image_to(instance, filename):
    return 'grant/%s/%s' % (
        now().strftime("%Y%m%d"),
        instance.slug
    )


class Grant(TimestampedModel):

    # Autogenerated model fields
    slug = models.SlugField(db_index=True, max_length=255, unique=True)
    foundation = models.ForeignKey(
        'foundations.Foundation', on_delete=models.CASCADE, related_name='grants'
    )

    # Required model fields
    title = models.CharField(max_length=255)
    description = models.TextField()
    minAmountPerGrantee = models.IntegerField()
    state = models.IntegerField(choices=[state.value for state in GrantState])

    # Optional model fields
    tags = models.ManyToManyField(
        'grants.Tag', related_name='grants'
    )
    externalWebsite = models.URLField()
    allowDonations = models.BooleanField(default=True)
    otherAwards = models.CharField()
    otherDetails = models.CharField()

    # Other metadata
    img = models.FileField(
        upload_to=upload_image_to,
        blank=True,
        editable=True)

    def __str__(self):
        return self.title
