# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-10-05 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundations', '0001_initial'),
        ('grants', '0001_initial'),
        ('profiles', '0003_profile_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_grants',
            field=models.ManyToManyField(related_name='favorited_grants_by', to='grants.Grant'),
        ),
        migrations.AddField(
            model_name='profile',
            name='follows_foundation',
            field=models.ManyToManyField(related_name='followed_by', to='foundations.Foundation'),
        ),
    ]
