# Generated by Django 2.2.6 on 2019-10-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20191005_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_grants',
        ),
    ]
