# Generated by Django 2.2.6 on 2019-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
        ('profiles', '0005_remove_profile_favorite_grants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorites',
        ),
        migrations.AddField(
            model_name='profile',
            name='favorite_grants',
            field=models.ManyToManyField(related_name='favorited_by', to='grants.Grant'),
        ),
    ]
