# Generated by Django 2.2.6 on 2019-10-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20191013_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorite_grants',
            field=models.ManyToManyField(related_name='favorited_grants_by', to='grants.Grant'),
        ),
    ]
